fix(build): add platform validation for amd64 and arm64 builds in Makefile
Signed-off-by: cuisongliu <cuisongliu@qq.com>

diff --git a/.github/workflows/services.yml b/.github/workflows/services.yml
--- a/.github/workflows/services.yml
+++ b/.github/workflows/services.yml
@@ -111,6 +111,12 @@ jobs:
           GOARCH=amd64 make build
           mv bin/manager bin/service-${MODULE}-amd64
           chmod +x bin/service-${MODULE}-amd64
+          file bin/service-${MODULE}-amd64
+          file bin/service-${MODULE}-amd64 | grep -q 'x86-64'
+          if [ $? -ne 0 ]; then
+              echo "amd64 platform build failed"
+              exit 1
+          fi
 
       - name: Build ${{ matrix.module }} arm64
         working-directory: service/${{ matrix.module }}
@@ -120,6 +126,12 @@ jobs:
           GOARCH=arm64 make build
           mv bin/manager bin/service-${MODULE}-arm64
           chmod +x bin/service-${MODULE}-arm64
+          file bin/service-${MODULE}-arm64
+          file bin/service-${MODULE}-arm64 | grep -q 'aarch64'
+          if [ $? -ne 0 ]; then
+              echo "arm64 platform build failed"
+              exit 1
+          fi
 
       - name: Expose git commit data
         uses: rlespinasse/git-commit-data-action@v1
